### ISSUE TITLE
Mistakes in Row-Only Attention ?

### ISSUE THREAD

**Issue by spyflying** [lucidrains/global-self-attention-network#1]
https://github.com/lucidrains/global-self-attention-network/blob/aa0b7d14f384df8fa85f5e904ed03dfc58e78e7d/gsa_pytorch/gsa_pytorch.py#L79

It seems there are dimension errors in row-only attention. I think the right version may be as below:
``` 
Py = einsum('xir,rd->xid', Iy, self.rel_columns)
# Sy = einsum('ndxy,xid->nixy', q, Py)
Sy = einsum('ndxy,yid->nixy', q, Py)
# rel_pos_out = einsum('nixy,neiy->nexy', Sy, Yh)
rel_pos_out = einsum('nixy,nexi ->nexy', Sy, Yh)
```

Could you please check it?

**Comment by lucidrains** [comment]
@spyflying yes, you are right! fixed in the latest!
