### ISSUE TITLE
Two possible errors in the current implementation.

### ISSUE THREAD

**Issue by angshine** [lucidrains/global-self-attention-network#2]
Hi, thanks for the fantastic work reimplementing so many transformers!

I think there might be two possible errors in the implementation. The first one is already mentioned in #1, and the second one relates to the relative position embedding and the indexer. Since there are `2 * L - 1` possible relative positions, the correct `calc_reindexing_tensor` and relative  position embedding might be:

```python
def calc_reindexing_tensor(l, L, device):
    """
    Args:
        l: image height / width.
        L: max_rel_shift, can be equal to img h / w or smaller.
    Returns:
        indexer_{xir}: indexing mask used to index the rel_pos_emb
     """
    x = torch.arange(l, device = device)[:, None, None]
    i = torch.arange(l, device = device)[None, :, None]
    r = torch.arange(-(L-1), L, device=device)[None, None, :]  # [-(L-1) ~ L-1]
    mask = ((i - x) == r) & ((i - x).abs() <= L)  # `& ((i - x).abs() <= L)` is optional in this setup.
                                                  # (only store the embeddings of possible relative shifts)
    return mask.float()
```
and, 
```python
self.rel_rows = nn.Parameter(torch.randn(2*max_rel_shift-1, dim_key))
self.rel_columns = nn.Parameter(torch.randn(2*max_rel_shift-1, dim_key))
```

Here is my full implementation based on yours : ) 
[gsa_pytorch.py](https://gist.github.com/angshine/befa27fb6787917348137f1a6fd8c778)

**Comment by lucidrains** [comment]
@angshine thank you! I have fixed the implementation in the latest commit :)

**Comment by lucidrains** [comment]
@angshine is this working for you as advertised in the paper?

**Comment by angshine** [comment]
> @angshine is this working for you as advertised in the paper?

I didn't try to reproduce their result but just tried using it in another project. So this is just my understanding of their method and no guarantee of correctness.
